# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0b4bd00b8e53b4a0996189ad5ecaf973d65be2f6cb5c6623d8bf75c9e5f7d2c0d1f698928446f8d0a597aee21d2467251c6998d334fa2e78467c1057d758e9a

test:
  secret_key_base: 712b06e50a6819ce543872500bb83adede0e513c9c75c9df6dafc56684fae7b77b2876a5014cc1a77072b7705b64be03e80b2fba8ff39f32c36995aaeecd4869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
